package github.com.st235.facialprocessing.presentation.theme

import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF984718)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFFFFDBCC)
val lightOnPrimaryContainer = Color(0xFF351000)
val lightSecondary = Color(0xFF9C413F)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFFFDAD7)
val lightOnSecondaryContainer = Color(0xFF410005)
val lightTertiary = Color(0xFFA83639)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFFFDAD8)
val lightOnTertiaryContainer = Color(0xFF410006)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFFFFBFF)
val lightOnBackground = Color(0xFF2D1600)
val lightSurface = Color(0xFFFFFBFF)
val lightOnSurface = Color(0xFF2D1600)
val lightSurfaceVariant = Color(0xFFF4DED5)
val lightOnSurfaceVariant = Color(0xFF52443D)
val lightOutline = Color(0xFF85736C)
val lightInverseOnSurface = Color(0xFFFFEEE1)
val lightInverseSurface = Color(0xFF4B2800)
val lightInversePrimary = Color(0xFFFFB693)
val lightSurfaceTint = Color(0xFF984718)
val lightOutlineVariant = Color(0xFFD7C2B9)
val lightScrim = Color(0xFF000000)

val darkPrimary = Color(0xFFFFB693)
val darkOnPrimary = Color(0xFF562000)
val darkPrimaryContainer = Color(0xFF7A3001)
val darkOnPrimaryContainer = Color(0xFFFFDBCC)
val darkSecondary = Color(0xFFFFB3AE)
val darkOnSecondary = Color(0xFF5F1415)
val darkSecondaryContainer = Color(0xFF7E2A29)
val darkOnSecondaryContainer = Color(0xFFFFDAD7)
val darkTertiary = Color(0xFFFFB3B0)
val darkOnTertiary = Color(0xFF680210)
val darkTertiaryContainer = Color(0xFF881D24)
val darkOnTertiaryContainer = Color(0xFFFFDAD8)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF2D1600)
val darkOnBackground = Color(0xFFFFDCC0)
val darkSurface = Color(0xFF2D1600)
val darkOnSurface = Color(0xFFFFDCC0)
val darkSurfaceVariant = Color(0xFF52443D)
val darkOnSurfaceVariant = Color(0xFFD7C2B9)
val darkOutline = Color(0xFFA08D85)
val darkInverseOnSurface = Color(0xFF2D1600)
val darkInverseSurface = Color(0xFFFFDCC0)
val darkInversePrimary = Color(0xFF984718)
val darkSurfaceTint = Color(0xFFFFB693)
val darkOutlineVariant = Color(0xFF52443D)
val darkScrim = Color(0xFF000000)


val seed = Color(0xFFFDD2BF)